[package]
name = "strand_software_rasterizer"
version = "0.1.0"
edition = "2024"

[package.metadata.bevy.asset_metadata]
shaders = { type = "WgslShader" }

[dependencies]
bevy = { version = "0.17.2", features=["experimental_pbr_pcss"] }
bytemuck = "1.22.0"
serde = "1.0.219"
fluent-uri = { version = "0.3.2", features = ["serde"] }
serde_json = "1.0.140"
anyhow = "1.0.97"
# bevy_radix_sort = "0.15.0"
bevy_wgsl_utils = { git = "https://github.com/AllenPocketGamer/bevy_wgsl_utils.git", branch = "master" }
bevy_panorbit_camera = "0.31.0"
# bevy-inspector-egui = { git = "https://github.com/jakobhellermann/bevy-inspector-egui.git", rev = "8d7580b304c7202054e5d821f6269e1e32b58712" }
bevy_egui = "0.38.0"
offset-allocator = "0.2"
range-alloc = "0.1.4"
nonmax = "0.5.5"